version: 2.4.0
atlas_user: "zealic"

boot_command:
  - "<esc><wait>"
  - "install <wait>"
  - " preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ks.cfg <wait>"
  - "debian-installer=en_US <wait>"
  - "auto <wait>"
  - "locale=en_US <wait>"
  - "kbd-chooser/method=us <wait>"
  - "keyboard-configuration/xkb-keymap=us <wait>"
  - "netcfg/get_hostname=localhost <wait>"
  - "netcfg/get_domain=localdomain <wait>"
  - "fb=false <wait>"
  - "debconf/frontend=noninteractive <wait>"
  - "console-setup/ask_detect=false <wait>"
  - "console-keymaps-at/keymap=us <wait>"
  - "grub-installer/bootdev=/dev/vda <wait>"
  - "<enter><wait>"

variables:
  default: {
    "headless": "false",
    "iso_url": "https://mirrors.tuna.tsinghua.edu.cn/debian-cd/9.1.0/amd64/iso-cd/debian-9.1.0-amd64-netinst.iso",
    "iso_checksum": "ddd8f6542dae8baf410e90b9ae0fe986",
    "iso_checksum_type": "md5",
    "mirror_host": "mirrors.tuna.tsinghua.edu.cn",
    "mirror_host.cn": "mirrors.tuna.tsinghua.edu.cn",
    "security_host": "security.debian.org",
    "security_host.cn": "mirrors.tuna.tsinghua.edu.cn"
  }
  push: {
    "headless": "true",
    "iso_url": "http://mirrors.kernel.org/debian-cd/9.1.0/amd64/iso-cd/debian-9.1.0-amd64-netinst.iso",
    "iso_checksum": "ddd8f6542dae8baf410e90b9ae0fe986",
    "iso_checksum_type": "md5",
    "mirror_host": "httpredir.debian.org",
    "mirror_host.cn": "mirrors.ustc.edu.cn",
    "security_host": "security.debian.org",
    "security_host.cn": "mirrors.ustc.edu.cn"
  }

remote-shell:
  # System Base
  - [
      "scripts/vagrant.sh",
      "scripts/packages.sh",
      "scripts/docker.sh"
    ]
  # Virtual Macine required
  - "scripts/vm-tools.sh"
  # Fuck GFW
  - "scripts/fuck_gfw.sh"
  # Cloud
  - "scripts/cloud-init.sh"
  # Cleanup
  - "scripts/cleanup.sh"
